### ISSUE TITLE
drawTextBox may cause exception that will kill all remaining drawing

### ISSUE THREAD

**Issue by nameouschangey** [nameouschangey/STORMWORKS_VSCodeExtension#18]
15/12/2021 10:52:04 TickHandler - OnLineRead - Exception Continuing - TEXTBOX|1|1|0|20|7|0|0|Home - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at System.String.LastIndexOf(String value, Int32 startIndex, Int32 count)
   at STORMWORKS_Simulator.DrawTextbox.Handle(MainVM vm, String[] commandParts) in C:\Workspaces\STORMWORKS_VSCodeExtension\CsharpSimulator\STORMWORKS_Simulator\src\PipedCommands\DrawingCommands.cs:line 238
   at STORMWORKS_Simulator.TickHandler.<>c__DisplayClass6_0.<OnLineRead>b__0() in C:\Workspaces\STORMWORKS_VSCodeExtension\CsharpSimulator\STORMWORKS_Simulator\src\TickHandler.cs:line 86
   
   
 (Fixed)

**Comment by nameouschangey** [comment]
Fixed and closed
